package entity;
// Generated 2015-10-30 14:40:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Actor generated by hbm2java
 */
public class Actor  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private Set casts = new HashSet(0);

    public Actor() {
    }

	
    public Actor(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public Actor(String firstName, String lastName, Set casts) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.casts = casts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Set getCasts() {
        return this.casts;
    }
    
    public void setCasts(Set casts) {
        this.casts = casts;
    }




}


