package entity;
// Generated 2015-10-30 14:40:09 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlTransient;




/**
 * Cast generated by hbm2java
 */
public class Cast  implements java.io.Serializable {


     private Integer id;
     private Actor actor;
     private Movie movie;

    public Cast() {
    }

    public Cast(Actor actor, Movie movie) {
       this.actor = actor;
       this.movie = movie;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @XmlTransient
    public Actor getActor() {
        return this.actor;
    }
    
    public void setActor(Actor actor) {
        this.actor = actor;
    }
    
    @XmlTransient
    public Movie getMovie() {
        return this.movie;
    }
    
    public void setMovie(Movie movie) {
        this.movie = movie;
    }




}


