package entity;
// Generated 2015-10-30 14:40:09 by Hibernate Tools 4.3.1



/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private Integer id;
     private Show show;
     private User user;
     private boolean checked;
     private boolean ok;
     private int seat;

    public Reservation() {
    }

    public Reservation(Show show, User user, boolean checked, boolean ok, int seat) {
       this.show = show;
       this.user = user;
       this.checked = checked;
       this.ok = ok;
       this.seat = seat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Show getShow() {
        return this.show;
    }
    
    public void setShow(Show show) {
        this.show = show;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public boolean isChecked() {
        return this.checked;
    }
    
    public void setChecked(boolean checked) {
        this.checked = checked;
    }
    public boolean isOk() {
        return this.ok;
    }
    
    public void setOk(boolean ok) {
        this.ok = ok;
    }
    public int getSeat() {
        return this.seat;
    }
    
    public void setSeat(int seat) {
        this.seat = seat;
    }




}


