package entity;
// Generated 2016-01-21 21:53:42 by Hibernate Tools 4.3.1



/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private ReservationId id;
     private Show show;
     private User user;
     private boolean checked;
     private boolean ok;

    public Reservation() {
    }

    public Reservation(ReservationId id, Show show, User user, boolean checked, boolean ok) {
       this.id = id;
       this.show = show;
       this.user = user;
       this.checked = checked;
       this.ok = ok;
    }
   
    public ReservationId getId() {
        return this.id;
    }
    
    public void setId(ReservationId id) {
        this.id = id;
    }
    public Show getShow() {
        return this.show;
    }
    
    public void setShow(Show show) {
        this.show = show;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public boolean isChecked() {
        return this.checked;
    }
    
    public void setChecked(boolean checked) {
        this.checked = checked;
    }
    public boolean isOk() {
        return this.ok;
    }
    
    public void setOk(boolean ok) {
        this.ok = ok;
    }




}


