package entity;
// Generated 2015-10-30 14:40:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Show generated by hbm2java
 */
public class Show  implements java.io.Serializable {


     private Integer id;
     private Movie movie;
     private Room room;
     private Date time;
     private Set reservations = new HashSet(0);

    public Show() {
    }

	
    public Show(Movie movie, Room room, Date time) {
        this.movie = movie;
        this.room = room;
        this.time = time;
    }
    public Show(Movie movie, Room room, Date time, Set reservations) {
       this.movie = movie;
       this.room = room;
       this.time = time;
       this.reservations = reservations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Movie getMovie() {
        return this.movie;
    }
    
    public void setMovie(Movie movie) {
        this.movie = movie;
    }
    public Room getRoom() {
        return this.room;
    }
    
    public void setRoom(Room room) {
        this.room = room;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


