package entity;
// Generated 2015-10-30 14:40:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlTransient;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String password;
     private int type;
     private String email;
     private Set reservations = new HashSet(0);

    public User() {
    }

	
    public User(String name, int type, String email) {
        this.name = name;
        this.type = type;
        this.email = email;
    }
    public User(String name, String password, int type, String email, Set reservations) {
       this.name = name;
       this.password = password;
       this.type = type;
       this.email = email;
       this.reservations = reservations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @XmlTransient
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


